name: Static Site

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - id: 'checkout'
        uses: 'actions/checkout@v4'

      # configure gcloud `setup-gcloud` automatically
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/763598444916/locations/global/workloadIdentityPools/github/providers/my-repo'
          service_account: 'my-service-account@cs1660-420316.iam.gserviceaccount.com'

      # upload files to GCS
      - id: 'upload-files'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: './index.html'
          destination: 'cs1660a5-bucket'
